"""
API v1 Schemas
Standardized schemas for API responses and error handling.
"""

from .common import APIError, ErrorResponse, SuccessResponse, PaginationParams, ListResponse
from .exceptions import (
    APIException,
    NotFoundException,
    ValidationException,
    ConflictException,
    RateLimitException,
    ServiceUnavailableException,
    SessionNotFoundException,
    ChapterNotFoundException,
    OutlineNotFoundException,
    DraftVersionNotFoundException,
    IFLineNotFoundException,
    PlotThreadNotFoundException,
    StyleNotFoundException,
    CharacterNotFoundException,
    ItemNotFoundException,
    LocationNotFoundException,
    FactionNotFoundException,
    WorldSettingNotFoundException,
    RuleNotFoundException,
    ImportVersionUnsupportedException,
    EntityNotFoundException,
    TaskNotFoundException,
    SnapshotNotFoundException,
    ArchiveNotFoundException,
    GenreNotFoundException,
    AIServiceException,
    AIQuotaExceededException,
)

__all__ = [
    "APIError",
    "ErrorResponse",
    "SuccessResponse",
    "PaginationParams",
    "ListResponse",
    "APIException",
    "NotFoundException",
    "ValidationException",
    "ConflictException",
    "RateLimitException",
    "ServiceUnavailableException",
    "SessionNotFoundException",
    "ChapterNotFoundException",
    "OutlineNotFoundException",
    "DraftVersionNotFoundException",
    "IFLineNotFoundException",
    "PlotThreadNotFoundException",
    "StyleNotFoundException",
    "CharacterNotFoundException",
    "ItemNotFoundException",
    "LocationNotFoundException",
    "FactionNotFoundException",
    "WorldSettingNotFoundException",
    "RuleNotFoundException",
    "ImportVersionUnsupportedException",
    "EntityNotFoundException",
    "TaskNotFoundException",
    "SnapshotNotFoundException",
    "ArchiveNotFoundException",
    "GenreNotFoundException",
    "AIServiceException",
    "AIQuotaExceededException",
]