# Auto Novel Writer - Pydantic Schemas
# Centralized validation and serialization models

from .common_schemas import (
    ErrorResponse,
    ValidationErrorResponse,
    PaginationParams,
    PaginatedResponse,
    SuccessResponse,
    MessageResponse,
    TimestampedResponse,
    sanitize_text,
    validate_chinese_name,
    validate_no_special_chars,
    validate_date_range,
    validate_positive_id,
    validate_non_empty,
)

from .request_schemas import (
    # Character requests
    CharacterCreateRequest,
    CharacterUpdateRequest,
    CharacterRelationshipCreateRequest,
    CharacterStorylineCreateRequest,
    # World entity requests
    ItemCreateRequest,
    ItemUpdateRequest,
    LocationCreateRequest,
    LocationUpdateRequest,
    FactionCreateRequest,
    FactionUpdateRequest,
    WorldSettingCreateRequest,
    WorldSettingUpdateRequest,
    RuleCreateRequest,
    RuleUpdateRequest,
    # Chapter requests
    OutlineCreateRequest,
    OutlineUpdateRequest,
    ChapterCreateRequest,
    ChapterUpdateRequest,
    IFLineCreateRequest,
    IFLineUpdateRequest,
    DraftVersionCreateRequest,
    PlotThreadCreateRequest,
    PlotThreadUpdateRequest,
    # Chat requests
    ChatMessageCreateRequest,
    ChatSessionCreateRequest,
    # AI requests
    GenerateRequest,
    ReviewRequest,
    ExtractEntitiesRequest,
    # Agent requests
    ContextRequest,
    ExtractRequest,
    # Settings requests
    WritingSettingsUpdateRequest,
    # Import/Export requests
    ImportRequest,
    ImportZipRequest,
    ExportDataRequest,
)

from .response_schemas import (
    # Character responses
    CharacterResponse,
    CharacterRelationshipResponse,
    CharacterStorylineResponse,
    # World entity responses
    ItemResponse,
    LocationResponse,
    FactionResponse,
    WorldSettingResponse,
    RuleResponse,
    # Chapter responses
    OutlineResponse,
    ChapterResponse,
    IFLineResponse,
    DraftVersionResponse,
    PlotThreadResponse,
    AIInspectionResultResponse,
    # Chat responses
    ChatMessageResponse,
    ChatSessionResponse,
    ExtractedEntityResponse,
    # AI responses
    ReviewResponse,
    # Agent responses
    ContextResponse,
    ExtractResponse,
    # Settings responses
    WritingSettingsResponse,
    WritingStyleResponse,
    # Export/Import responses
    ExportDataResponse,
    ImportSummaryResponse,
)

__all__ = [
    # Common
    "ErrorResponse",
    "ValidationErrorResponse",
    "PaginationParams",
    "PaginatedResponse",
    "SuccessResponse",
    "MessageResponse",
    "TimestampedResponse",
    "sanitize_text",
    "validate_chinese_name",
    "validate_no_special_chars",
    "validate_date_range",
    "validate_positive_id",
    "validate_non_empty",
    # Request schemas
    "CharacterCreateRequest",
    "CharacterUpdateRequest",
    "CharacterRelationshipCreateRequest",
    "CharacterStorylineCreateRequest",
    "ItemCreateRequest",
    "ItemUpdateRequest",
    "LocationCreateRequest",
    "LocationUpdateRequest",
    "FactionCreateRequest",
    "FactionUpdateRequest",
    "WorldSettingCreateRequest",
    "WorldSettingUpdateRequest",
    "RuleCreateRequest",
    "RuleUpdateRequest",
    "OutlineCreateRequest",
    "OutlineUpdateRequest",
    "ChapterCreateRequest",
    "ChapterUpdateRequest",
    "IFLineCreateRequest",
    "IFLineUpdateRequest",
    "DraftVersionCreateRequest",
    "PlotThreadCreateRequest",
    "PlotThreadUpdateRequest",
    "ChatMessageCreateRequest",
    "ChatSessionCreateRequest",
    "GenerateRequest",
    "ReviewRequest",
    "ExtractEntitiesRequest",
    "ContextRequest",
    "ExtractRequest",
    "WritingSettingsUpdateRequest",
    "ImportRequest",
    "ImportZipRequest",
    "ExportDataRequest",
    # Response schemas
    "CharacterResponse",
    "CharacterRelationshipResponse",
    "CharacterStorylineResponse",
    "ItemResponse",
    "LocationResponse",
    "FactionResponse",
    "WorldSettingResponse",
    "RuleResponse",
    "OutlineResponse",
    "ChapterResponse",
    "IFLineResponse",
    "DraftVersionResponse",
    "PlotThreadResponse",
    "AIInspectionResultResponse",
    "ChatMessageResponse",
    "ChatSessionResponse",
    "ExtractedEntityResponse",
    "ReviewResponse",
    "ContextResponse",
    "ExtractResponse",
    "WritingSettingsResponse",
    "WritingStyleResponse",
    "ExportDataResponse",
    "ImportSummaryResponse",
]
